### ISSUE TITLE
Integrationsrelease auf MT funktioniert zur Zeit nicht

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_tenants#1]
Die Integrationsumgebung hat einen alten Stand. Vor dem nächsten prod Release diese Umgebung aktualisieren.

**Comment by kronn** [comment]
Das Basis-Image war nicht mehr aktuell genug für den OpenShift-Source2Image-Build. Also habe ich das base-image neu gebaut, jetzt funktioniert es wieder. Ich habe auch das nächtliche Deployment wieder aktiviert.
