### ISSUE TITLE
MAILS: No-Reply Mails gehen an André

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito_tenants#7]
Timebox: 4h

Siehe: https://help.puzzle.ch/#ticket/zoom/3569

Bei manchen (theoretisch allen?) Tenants gehen no-reply Mail bounces u.A auch an André.

Bereits geprüft:
- André ist kein Abonnent bei den jeweiligen no-reply Mailinglisten
- E-Mail Addresse ist nicht im Code hinterlegt.

Offene Fragen:
- Werden/wurden no-reply Mails dennoch an den ursprünglichen Absender gesendet?
- Soll jemand anderes diese Mails weiterhin empfangen?

**Comment by mtnstar** [comment]
https://help.puzzle.ch/#ticket/zoom/3569
